### ISSUE TITLE
Create the Text bindings

### ISSUE THREAD

**Issue by LSViana** [LSViana/ydotnet#12]
Implement the bindings for the [Text struct](https://github.com/y-crdt/y-crdt/blob/65c60aa940d306123db8f21df926c527422c46a3/yrs/src/types/text.rs#L94) based on the [exposed bindings](https://github.com/y-crdt/y-crdt/blob/main/yffi/src/lib.rs).

- [x]  Create class definition
- [x]  `ytext`
- [x]  `ytext_len`
- [x]  `ytext_string`
- [x]  `ytext_insert`
- [x]  `ytext_format`
- [x]  `ytext_chunks`
- [x]  `ytext_insert_embed`
- [x]  `ytext_remove_range`
- [x]  `ytext_observe`
- [x]  `ytext_unobserve`
- [x]  `ytext_event_target`
- [x]  `ytext_event_path`
- [x]  `ytext_event_delta`
- [x]  `ytext_delta_destroy`

For each bound method, the implementation and unit tests must be written.

**Comment by LSViana** [comment]
All the bindings have been finished. Waiting on the team's comments about how to properly test `ytext_event_path` before merging this PR.

**Comment by goldsam** [comment]
Who is the team? You seem to be the only contributor.

**Comment by LSViana** [comment]
I'm going ahead and merging this PR now. Some tests might be added later based on the team's response about how to properly test the event path feature of `YText` events.
