### ISSUE TITLE
Windows binary produced via cross-compilation consumes all system memory.

### ISSUE THREAD

**Issue by goldsam** [LSViana/ydotnet#18]
@LSViana I'm seeing memory consumption grow without bound for some of the map-related tests (InsertMap for example) on windows x64. Could you take a look at my [github workflow](https://github.com/goldsam/ydotnet/blob/binaries/.github/workflows/build.yml). I'm current doing a cross-compilation when maybe building on windows might be the best approach.

I'm also [patching the `yffi/Cargo.toml`](https://github.com/goldsam/ydotnet/blob/binaries/resources/patch/yffi/Cargo.toml.patch) to produce a dynamic library. What was your approach to building your local binary assets?

**Comment by goldsam** [comment]
This is cleared up by #19 which references custom yrs build

**Comment by LSViana** [comment]
@goldsam Just to give you some extra details for your mentions here:

> I'm seeing memory consumption grow without bound for some of the map-related tests (InsertMap for example) on windows x64.

It's possible that there are some memory leaks in some operations, I have plans to check these once I'm done creating all bindings.

> I'm also [patching the yffi/Cargo.toml](https://github.com/goldsam/ydotnet/blob/binaries/resources/patch/yffi/Cargo.toml.patch) to produce a dynamic library.

Yes, that's what I'm doing currently as well. However, I'll look into the Cargo CLI options later to verify if it's possible to specify the `crate-type` through the commands so the main repository doesn't have to change.

But this, just like the issue mentioned above, will be focused only after the bindings are done.
