### ISSUE TITLE
youtput_read_json_undefined isn't an exported yffi symbol

### ISSUE THREAD

**Issue by goldsam** [LSViana/ydotnet#19]
@LSViana I'm getting the following error against v0.16.10 of yrs:
```
System.EntryPointNotFoundException : Unable to find an entry point named 'youtput_read_json_undefined' in DLL 'yrs.dll'.
```
Are you using a modified version of the library? I'm not finding that symbol in any branch.

**Comment by LSViana** [comment]
Hey, @goldsam!

Yes, I'm using a modified version with extra features and some patches that didn't land on the main repository yet. Please, use [this repository](https://github.com/LSViana/y-crdt) as the main source to compile the Rust binary.

If you have any other issues, please let me know.

**Comment by LSViana** [comment]
By the way, this and any other kind of problems will be cleared later when I finish the main batch of work in this repository and create a README.

**Comment by goldsam** [comment]
Thanks for the quick response! I see that you're busy cranking out the code. I'm excited about this project and want to help out 😉

**Comment by goldsam** [comment]
That works great! I see 4 tests fail (165 pass) on main. Is that expected?
