### ISSUE TITLE
Create the Doc bindings

### ISSUE THREAD

**Issue by LSViana** [LSViana/ydotnet#3]
Implement the bindings for the [`Doc` struct](https://github.com/y-crdt/y-crdt/blob/main/yrs/src/doc.rs#L61-L63) based on the [exposed bindings](https://github.com/y-crdt/y-crdt/blob/main/yffi/src/lib.rs).

- [x] Create `Doc` class definition
- [x] `ydoc_new`
- [x] `ydoc_clone`
- [x] `ydoc_destroy`
- [x] `ydoc_new_with_options`
- [x] `ydoc_id`
- [x] `ydoc_guid`
- [x] `ydoc_collection_id`
- [x] `ydoc_should_load`
- [x] `ydoc_auto_load`
- [x] `ydoc_observe_updates_v1`
- [x] `ydoc_unobserve_updates_v1`
- [x] `ydoc_observe_updates_v2`
- [x] `ydoc_unobserve_updates_v2`
- [x] `ydoc_observe_after_transaction`
- [x] `ydoc_unobserve_after_transaction`
- [x] `ydoc_clear`
- [x] `ydoc_observe_clear`
- [x] `ydoc_unobserve_clear`
- [x] `ydoc_read_transaction`
- [x] `ydoc_write_transaction`
- [x] `ydoc_load`
- [x] `ydoc_observe_subdocs`
- [x] `ydoc_unobserve_subdocs`

For each bound method, the implementation and unit tests must be written.

**Comment by LSViana** [comment]
Hi, @Horusiath!

I'd like you to take a look at the work I'm doing to create the .NET bindings for Yrs.

The "core" of the work has been happening mostly on the [`Doc`](https://github.com/LSViana/ydotnet/pull/4/files#diff-c308ddd28f0dfe69b8a4b6bdb75d8ab6fd7ec0bb3348ac5f46481bc232c92086) and [`DocChannel`](https://github.com/LSViana/ydotnet/pull/4/files#diff-833f05127faef4cc5609e3123945ee3e3ee830dd1573433ab3a1f8363ed3e036) classes. They're the public and the native binding classes, respectively.

Everything else around them are tests or helper definitions to interact with the FFI exposed by YFFI. I've been moving slow because I can only work on this in my spare time (and this is not my only side project), but there's been steady progress here.

What do you think?

**Comment by LSViana** [comment]
Also, I'd like to ask you about the [`Guid()` method](https://github.com/LSViana/ydotnet/pull/4/files#diff-833f05127faef4cc5609e3123945ee3e3ee830dd1573433ab3a1f8363ed3e036R23) exposed by YFFI as `y_doc_guid`.

I noticed that, sometimes, the UUID v4 generated contains some internal values like `11` (decimal) that are translated to `0B`. Then, [when they're formatted to string](https://github.com/y-crdt/y-crdt/blob/main/yrs/src/lib.rs#L517-L535), it becomes `B` (or `b`) only and the final string doesn't match the GUID format that C# expects. Is that fixable somehow? I'd not like to touch (or request changes to) the Yrs code, then if you have a less invasive suggestion, that'd be nice.

**Comment by Horusiath** [comment]
> I noticed that, sometimes, the UUID v4 generated contains some internal values like `11` (decimal) that are translated to `0B`. Then, [when they're formatted to string](https://github.com/y-crdt/y-crdt/blob/main/yrs/src/lib.rs#L517-L535), it becomes `B` (or `b`) instead of `0B` and the final string doesn't match the GUID format that C# expects (it's like characters are missing). Is that fixable somehow? I'd not like to touch (or request changes to) the Yrs code, then if you have a less invasive suggestion, that'd be nice.

I think it should be doable. However keep in mind that the source of that uuid is originally in JavaScript, so it's possible that someone is using arbitrary strings in there - which is also a reason why I went with string representation in Rust.
