### ISSUE TITLE
JsonArray is missing in Output

### ISSUE THREAD

**Issue by SebastianStehle** [LSViana/ydotnet#40]
Hi,

we have Map for YMap and Object for json objects. But only Array for YArray and nothing for Json Arrays.

**Comment by LSViana** [comment]
Hi, @SebastianStehle!

The name probably isn't optimal here but please try the [`Output.Collection` property](https://github.com/LSViana/ydotnet/blob/main/YDotNet/Document/Cells/Output.cs#L101).

**Comment by SebastianStehle** [comment]
Lol,

I have checked the output class at least 5 times, but I have not seen it. Thanks :)
