### ISSUE TITLE
NuGet handle

### ISSUE THREAD

**Issue by SebastianStehle** [LSViana/ydotnet#58]
Hi,

because I have accidentally pushed some packages to nuget without my Squidex prefix, I own packages like YDotNet now.

I think the only option is to also make you the owner, but I need your nuget username for that.

**Comment by LSViana** [comment]
Hi, @SebastianStehle!

Oh, that's not a problem. My NuGet user is `lsviana`.

Also, I'll ping @Horusiath and @dmonad here because they may be interested in being owners as well.

**Comment by dmonad** [comment]
It is probably easier if the current maintainer holds the account. Either one of you would be fine IMO. But please be available to transfer if someone else is taking over. We can also transfer the package to an organization in the future once the package is established..

**Comment by LSViana** [comment]
Since the ownership is now shared between @SebastianStehle and me, I'm closing this issue.
