### ISSUE TITLE
Demo client project problems

### ISSUE THREAD

**Issue by LSViana** [LSViana/ydotnet#64]
Using macOS, when running `npm install` in the `Demo/Demo/Client` directory, I got the following error:

<details><summary>Error details</summary>
<pre>npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-monaco-editor@0.42.0
npm ERR! Found: @types/react@18.2.24
npm ERR! node_modules/@types/react
npm ERR!   dev @types/react@"^18.2.15" from the root project
npm ERR!   @types/react@"*" from @types/react-dom@18.2.8
npm ERR!   node_modules/@types/react-dom
npm ERR!     dev @types/react-dom@"^18.2.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @types/react@"^17.x" from react-monaco-editor@0.42.0
npm ERR! node_modules/react-monaco-editor
npm ERR!   react-monaco-editor@"^0.42.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @types/react@17.0.71
npm ERR! node_modules/@types/react
npm ERR!   peer @types/react@"^17.x" from react-monaco-editor@0.42.0
npm ERR!   node_modules/react-monaco-editor
npm ERR!     react-monaco-editor@"^0.42.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/lsviana/.npm/_logs/2023-11-24T22_58_08_125Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/lsviana/.npm/_logs/2023-11-24T22_58_08_125Z-debug-0.log</pre>
</details>

I had to run the command `npm install --force` to make it work.

**Comment by LSViana** [comment]
Hi, @SebastianStehle!

Please, can you check this issue?

**Comment by SebastianStehle** [comment]
Yes, we can just downgrade react to v17.

**Comment by LSViana** [comment]
Closed by #66.
